name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test tests/AzdoScanner.Tests/AzdoScanner.Tests.csproj --configuration Release --no-build
      - name: Pack global tool
        run: |
          dotnet pack src/azdo-scanner/azdo-scanner.csproj --configuration Release --no-build --output ./artifacts
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: azdo-scanner-nupkg
          path: ./artifacts/*.nupkg
